### ISSUE TITLE
Test on Debian docker fails

### ISSUE THREAD

**Issue by melezhik** [jmaslak/Raku-Sys-HostAddr#1]
Hi! FYI.
http://repo.westus.cloudapp.azure.com/rakudist/reports/Sys%3A%3AHostAddr/debian/1580649570.txt

HTH

Aleksei

**Comment by jmaslak** [comment]
I'll do some investigation on this.  I'm a little baffled how literally "return Str" fails the type test of returning "Str", but on Debian there should be better output than we're getting here regardless (I should be returning a defined string on pretty much any Debian box).  I'll be in transit today so it might be a day or two for me to get to it unless I spot something really obvious.

**Comment by jmaslak** [comment]
Fixed in aa6cd210dade86cc96fee079d7914a0e88911c1e and documented in 7b5b8b0aace37eb0285a787c6800e1e2878c9129

**Comment by jmaslak** [comment]
Released as 0.1.2.

Thank you for your report!

**Comment by melezhik** [comment]
Yeah. Works now.

http://repo.westus.cloudapp.azure.com/rakudist/reports/Sys%3A%3AHostAddr/debian/1580733790.txt

BTW. You can replay the test whenever you need it.

https://github.com/melezhik/RakuDist/blob/master/README.md#testing-cpan-modules
